In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
df=pd.read_csv("../data/Groceries_dataset.csv")
df

,Member_number,Date,itemDescription
0,1808,21-07-2015,tropical fruit
1,2552,05-01-2015,whole milk
2,2300,19-09-2015,pip fruit
3,1187,12-12-2015,other vegetables
4,3037,01-02-2015,whole milk
...,...,...,...
38760,4471,08-10-2014,sliced cheese
38761,2022,23-02-2014,candy
38762,1097,16-04-2014,cake bar
38763,1510,03-12-2014,fruit/vegetable juice


In [33]:
df.head() #display 1st 5 records

,Member_number,Date,itemDescription
0,1808,21-07-2015,tropical fruit
1,2552,05-01-2015,whole milk
2,2300,19-09-2015,pip fruit
3,1187,12-12-2015,other vegetables
4,3037,01-02-2015,whole milk


In [34]:
#df = pd.read_excel("../data/dat.excel, sheet_name="sheet1"") #this is for the excel with multiple sheets

In [35]:
df.shape


(38765, 3)

In [36]:
df.tail()

,Member_number,Date,itemDescription
38760,4471,08-10-2014,sliced cheese
38761,2022,23-02-2014,candy
38762,1097,16-04-2014,cake bar
38763,1510,03-12-2014,fruit/vegetable juice
38764,1521,26-12-2014,cat food


In [37]:
df.columns

Index(['Member_number', 'Date', 'itemDescription'], dtype='str')

In [38]:
df.dtypes

Member_number      int64
Date                 str
itemDescription      str
dtype: object

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  str  
 2   itemDescription  38765 non-null  str  
dtypes: int64(1), str(2)
memory usage: 908.7 KB


In [40]:
df.describe()

,Member_number
count,38765.000000
mean,3003.641868
std,1153.611031
min,1000.000000
25%,2002.000000
50%,3005.000000
75%,4007.000000
max,5000.000000


In [41]:
df.isnull().sum()

Member_number      0
Date               0
itemDescription    0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(759)

In [43]:
#split the independent veriables
#loc uses the labels
#iloc uses the integer positions (no. starting from 0 to length of the data)
df
x = df.iloc[:, :-1].values
x

array([[1808, '21-07-2015'],
       [2552, '05-01-2015'],
       [2300, '19-09-2015'],
       ...,
       [1097, '16-04-2014'],
       [1510, '03-12-2014'],
       [1521, '26-12-2014']], shape=(38765, 2), dtype=object)

In [44]:
#split dependent variable
y = df.iloc[:, 2].values
y

<StringArray>
[          'tropical fruit',               'whole milk',
                'pip fruit',         'other vegetables',
               'whole milk',               'rolls/buns',
         'other vegetables',               'pot plants',
               'whole milk',           'tropical fruit',
 ...
            'bottled water',    'fruit/vegetable juice',
               'rolls/buns', 'long life bakery product',
                      'oil',            'sliced cheese',
                    'candy',                 'cake bar',
    'fruit/vegetable juice',                 'cat food']
Length: 38765, dtype: str

In [ ]:
# encoding the categorical data
#encoding the independent veriable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
x[:, 0] = labelencoder_X.fit_transform(x[:, 0])
print(x)

[[0 44.0 72000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 65750.0]
 [0 35.0 58000.0]
 [2 40.25 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [ ]:
# encoding the independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    [('country', OneHotEncoder(), [0])],
    remainder='passthrough'
)

x = ct.fit_transform(x)
x = x.astype(int)




In [ ]:
#split the data into the training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=45)


In [ ]:
x_test

array([[    0,     0,     1,    38, 61000],
       [    0,     1,     0,    50, 83000]])

In [ ]:
#Feature Scaling
#sc_X = (x[1] - mean) / standard deviation
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
x_train = sc_X.fit_transform(x_train)
x_test = sc_X.fit_transform(x_test)

In [ ]:
x_train

array([[-1.15470054,  1.58113883, -0.40824829, -1.6738105 , -1.09367203],
       [ 0.8660254 , -0.63245553, -0.40824829,  1.62150392,  1.65030797],
       [ 0.8660254 , -0.63245553, -0.40824829, -0.39229934,  0.33319757],
       [-1.15470054, -0.63245553,  2.44948974,  0.15691973, -1.31319043],
       [ 0.8660254 , -0.63245553, -0.40824829,  0.88921183,  0.88199357],
       [ 0.8660254 , -0.63245553, -0.40824829, -0.75844538, -0.65463523],
       [-1.15470054,  1.58113883, -0.40824829,  0.15691973,  0.19599857]])