In [2]:

import numpy as np

In [4]:
m = np.array([])
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [5]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [7]:
lspace = np.linspace(0, 10, 9)
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [8]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
num = np.matrix([[11, 121, 130],
                [613, 34, 13],
                [514, 50, 16]])

In [13]:
num

matrix([[ 11, 121, 130],
        [613,  34,  13],
        [514,  50,  16]])

In [14]:
type(num)

numpy.matrix

In [16]:
print("Main Diagonal elements : \n", np.diag(num))
print("\n Diagonal elements above main diagonal : \n", np.diag(num, 1))
print("\n Diagonal elements below main diagonal : \n", np.diag(num, -1))
print("\n Diagonal elements one step above main diagonal : \n", np.diag(num,2))
print("\n Diagonal elements one step below main diagonal : \n", np.diag(num,-2))

Main Diagonal elements : 
 [11 34 16]

 Diagonal elements above main diagonal : 
 [121  13]

 Diagonal elements below main diagonal : 
 [613  50]

 Diagonal elements one step above main diagonal : 
 [130]

 Diagonal elements one step below main diagonal : 
 [514]


In [17]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [18]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [24]:
p= np.ones([3, 3])

In [25]:
np.vstack([p, 2*p])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [27]:
np.hstack([p, 2*p, 3*p])

array([[1., 1., 1., 2., 2., 2., 3., 3., 3.],
       [1., 1., 1., 2., 2., 2., 3., 3., 3.],
       [1., 1., 1., 2., 2., 2., 3., 3., 3.]])

In [28]:
x=np.array([1, 2, 3])
y=np.array([4, 5, 6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [29]:
print(x + y)
print(x - y)

[5 7 9]
[-3 -3 -3]


In [30]:
print(x * y)
print(x / y)
print(x ** y)
print(x @ y)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
32


In [31]:
x.dot(y)

np.int64(32)

In [33]:
k = np.array([[1, 1, 1],
               [8, 8, 8]])
p = np.array([[1, 5, 1],
               [8, 0, 8]])

In [35]:
print(k + p)
print(k - p)
print(k * p)
print(k / p)
print(k ** p)


[[ 2  6  2]
 [16  8 16]]
[[ 0 -4  0]
 [ 0  8  0]]
[[ 1  5  1]
 [64  0 64]]
[[1.  0.2 1. ]
 [1.  inf 1. ]]
[[       1        1        1]
 [16777216        1 16777216]]


C:\Users\MSIS\AppData\Local\Temp\ipykernel_19904\3036010760.py:4: RuntimeWarning: divide by zero encountered in divide
  print(k / p)


In [37]:
z= np.array((y,2*y))
z

array([[ 4,  5,  6],
       [ 8, 10, 12]])

In [38]:
z.shape



(2, 3)

In [39]:
z.dtype

dtype('int64')

In [40]:
z = z.astype('f')
z.dtype

dtype('float32')

In [41]:
a = np.array([-4, -2, 1, 3, 5])
a.sum()

np.int64(3)

In [42]:
a.max()

np.int64(5)

In [43]:
a.min()

np.int64(-4)

In [44]:
a.mean()

np.float64(0.6)

In [45]:
a.std()

np.float64(3.2619012860600183)

In [46]:
a.argmax()

np.int64(4)

In [48]:
a.argmin() #returns the min and max numbers indexes

np.int64(0)

In [49]:
m=np.array([7,3,-2,0,100,25])

In [57]:
m.sum()

np.int64(133)

In [58]:
m.min()


np.int64(-2)

In [59]:
m.max()

np.int64(100)

In [60]:
m.mean()

np.float64(22.166666666666668)

In [61]:
m.std()

np.float64(35.91386299962113)

In [62]:
m.argmin()

np.int64(2)

In [63]:
m.argmax()

np.int64(4)

In [64]:
s= np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [66]:
s= np.arange(6)**2
s

array([ 0,  1,  4,  9, 16, 25])

In [67]:
s[0],s[4],s[-1]

(np.int64(0), np.int64(16), np.int64(25))

In [68]:
s[1:5]

array([ 1,  4,  9, 16])

In [70]:
s= np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [71]:
s[0],s[4],s[-1]


(np.int64(0), np.int64(16), np.int64(144))

In [72]:
s[-4:]

array([ 81, 100, 121, 144])

In [73]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [77]:
r = np.arange(100)
r.resize((10,10))
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [78]:
r[3,4]

np.int64(34)

In [79]:
r[2,1:4]

array([21, 22, 23])

In [81]:
r[:3, :-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [82]:
r[3, 3:6]

array([33, 34, 35])