In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [29]:
df=pd.read_csv("../data/data.csv")
df

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Germany,30.0,54000.0,No
2,Spain,38.0,61000.0,No
3,Germany,40.0,NaN,Yes
4,France,35.0,58000.0,Yes
5,Spain,NaN,52000.0,No
6,France,48.0,79000.0,Yes
7,Germany,50.0,83000.0,No
8,France,37.0,67000.0,Yes


In [30]:
df.head() #display 1st 5 records

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Germany,30.0,54000.0,No
2,Spain,38.0,61000.0,No
3,Germany,40.0,NaN,Yes
4,France,35.0,58000.0,Yes


In [31]:
#df = pd.read_excel("../data/dat.excel, sheet_name="sheet1"") #this is for the excel with multiple sheets

In [32]:
df.shape


(9, 4)

In [33]:
df.tail()

,Country,Age,Salary,Purchased
4,France,35.0,58000.0,Yes
5,Spain,NaN,52000.0,No
6,France,48.0,79000.0,Yes
7,Germany,50.0,83000.0,No
8,France,37.0,67000.0,Yes


In [34]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='str')

In [35]:
df.dtypes

Country          str
Age          float64
Salary       float64
Purchased        str
dtype: object

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    9 non-null      str    
 1   Age        8 non-null      float64
 2   Salary     8 non-null      float64
 3   Purchased  9 non-null      str    
dtypes: float64(2), str(2)
memory usage: 420.0 bytes


In [37]:
df.describe()

,Age,Salary
count,8.000000,8.000000
mean,40.250000,65750.000000
std,6.734771,11486.016343
min,30.000000,52000.000000
25%,36.500000,57000.000000
50%,39.000000,64000.000000
75%,45.000000,73750.000000
max,50.000000,83000.000000


In [38]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [56]:
#split the independent veriables
#loc uses the labels
#iloc uses the integer positions (no. starting from 0 to length of the data)
df
x = df.iloc[:, :-1].values
x

array([['France', 44.0, 72000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [55]:
#split dependent variable
y = df.iloc[:, 3].values
y

<StringArray>
['No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 9, dtype: str

In [57]:
# taking care of missing data
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:, 1:3])

x[:, 1:3] = imputer.transform(x[:, 1:3])
x


array([['France', 44.0, 72000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 65750.0],
       ['France', 35.0, 58000.0],
       ['Spain', 40.25, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [58]:
# encoding the categorical data
#encoding the independent veriable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
x[:, 0] = labelencoder_X.fit_transform(x[:, 0])
print(x)

[[0 44.0 72000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 65750.0]
 [0 35.0 58000.0]
 [2 40.25 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [59]:
# encoding the independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    [('country', OneHotEncoder(), [0])],
    remainder='passthrough'
)

x = ct.fit_transform(x)
x = x.astype(int)




In [60]:
#split the data into the training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=45)


In [61]:
x_test

array([[    0,     0,     1,    38, 61000],
       [    0,     1,     0,    50, 83000]])

In [62]:
#Feature Scaling
#sc_X = (x[1] - mean) / standard deviation
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
x_train = sc_X.fit_transform(x_train)
x_test = sc_X.fit_transform(x_test)

In [64]:
x_train

array([[-1.15470054,  1.58113883, -0.40824829, -1.6738105 , -1.09367203],
       [ 0.8660254 , -0.63245553, -0.40824829,  1.62150392,  1.65030797],
       [ 0.8660254 , -0.63245553, -0.40824829, -0.39229934,  0.33319757],
       [-1.15470054, -0.63245553,  2.44948974,  0.15691973, -1.31319043],
       [ 0.8660254 , -0.63245553, -0.40824829,  0.88921183,  0.88199357],
       [ 0.8660254 , -0.63245553, -0.40824829, -0.75844538, -0.65463523],
       [-1.15470054,  1.58113883, -0.40824829,  0.15691973,  0.19599857]])