1. # Create a constant array
		# Prints "[[ 7.  7.]
                #          [ 7.  7.]]"

In [2]:
import numpy as np
a=np.full((2,2), 7)
a

array([[7, 7],
       [7, 7]])


2. # Create an array filled with random values
         # Might print "[[ 0.91940167  0.08143941]
         #               [ 0.68744134  0.87236687]]"

In [5]:
a=np.random.random((2,2))
a

array([[0.60472026, 0.3606072 ],
       [0.59337033, 0.43540972]])

3. Create a NumPy array containing the numbers from 10 to 50. Display:

The array
Number of elements
Shape
Dimension
Data type

In [8]:
arr = np.arange(10,50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
arr.size

40

In [10]:
arr.shape

(40,)

In [11]:
arr.ndim

1

In [12]:
arr.dtype

dtype('int64')

4. Using NumPy, create:

A 1D array containing 10 zeros
A 3 × 3 array containing ones
A 4 × 4 identity matrix
An array containing numbers from 5 to 50 with a step size of 5.

In [14]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
one= np.ones([3,3])
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
iden=np.eye(4,4)
iden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
b=np.arange(5,51,5)
b

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

5. Create an array containing numbers from 1 to 24. Reshape it into:

4 × 6
6 × 4
2 × 3 × 4

Display the shape and ndim of each result.

In [22]:
arr=np.arange(1,25)
a=arr.reshape(4,6)
a


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [23]:
a.shape



(4, 6)

In [24]:
a.ndim

2

In [25]:
b=arr.reshape(6,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [26]:

b.shape

(6, 4)

In [27]:
b.ndim

2

In [28]:
c=arr.reshape(2,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [29]:
c.shape

(2, 3, 4)

In [30]:

c.ndim

3

6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

Write NumPy statements to display:

First element
Last element
Third element
First four elements
Last three elements

In [31]:
m = np.array([78, 85, 92, 67, 88, 73, 95, 81])
m[0]

np.int64(78)

In [32]:
m[-1]

np.int64(81)

In [33]:
m[2]

np.int64(92)

In [35]:
m[0:4]

array([78, 85, 92, 67])

In [36]:
m[-1:3:-1]

array([81, 95, 73, 88])

7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

Calculate:

a + b
a - b
a * b
a / b
Square of every element in a

In [37]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
a+b

array([15, 30, 45, 60, 75])

In [38]:
a-b

array([ 5, 10, 15, 20, 25])

In [39]:
a*b

array([  50,  200,  450,  800, 1250])

In [40]:
a/b

array([2., 2., 2., 2., 2.])

In [41]:
a**2

array([ 100,  400,  900, 1600, 2500])

8. Given:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

Find:

Total salary
Average salary
Highest salary
Lowest salary
Median salary
Standard deviation

In [42]:
s = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])
s.sum()


np.int64(290000)

In [44]:
s.mean()

np.float64(36250.0)

In [45]:
s.max()

np.int64(50000)

In [46]:
s.min()

np.int64(25000)

In [50]:
np.median(s)

np.float64(35000.0)

In [48]:
s.std()

np.float64(8317.902379807063)

9. Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

Using NumPy boolean indexing, find:

Marks greater than 75
Marks between 50 and 80
Number of students who scored below 50
Percentage of students who scored 60 or above

Do not use a Python for loop.

In [51]:
m = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
m[m>75]

array([78, 89, 90, 76, 84])

In [52]:
m[(m>50)&(m<80)]

array([78, 67, 55, 76])

In [53]:
np.sum(m<50)

np.int64(3)

In [61]:
 np.mean(m >= 60) * 100

np.float64(60.0)